sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
services:
  - rabbitmq 
env:
  - RABBITMQ_HOST=localhost RABBITMQ_PORT=61613 RABBITMQ_USER=guest RABBITMQ_PASSWORD=guest STD_HOST=localhost STD_PORT=61613 STD_USER=guest STD_PASSWORD=guest
install:
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - pip install virtualenv-api
script:
  - make travistests
